# Change these first
owner: BitWire # Your GitHub username
repo: deskhelper-status # Your Github repository name

# Add your sites here
sites:
  - name: Deskhelper Cloud
    url: https://server.deskhelper.de
  - name: Wieichnichtheisse.de
    url: https://wieichnichtheisse.de
  - name: Deskhelper Blog
    url: https://blog.deskhelper.de
  - name: Deskhelper Static Page
    url: https://deskhelper.de

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.deskhelper.de
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://deskhelper.de/favicon.png
  name: Deskhelper
  introTitle: "This is the Statuspage for my Deskhelper Pages, it is powered by **Upptime**."
  introMessage: "This is the Statuspage for my Deskhelper Pages, it is powered by **Upptime**, the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
